# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env file
        run: |
          touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          cat .env
      - name: Create .env.local file
        run: |
          touch .env.local
          echo NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }} >> .env.local
          echo SQUARE_ACCESS_TOKEN=${{ secrets.SQUARE_ACCESS_TOKEN }} >> .env.local
          echo SQUARE_LOCATION_ID=${{ secrets.SQUARE_LOCATION_ID }} >> .env.local
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.local
          echo CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} >> .env.local
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env.local
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env.local
          echo PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }} >> .env.local
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env.local
          echo JWT_SIGNING_PRIVATE_KEY=${{ secrets.JWT_SIGNING_PRIVATE_KEY }} >> .env.local
          echo USER_EMAIL=${{ secrets.USER_EMAIL }} >> .env.local
          echo USER_PASS=${{ secrets.USER_PASS }} >> .env.local
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env.local
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env.local
          echo NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }} >> .env.local
          echo NEXT_PUBLIC_SNIPCART_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_SNIPCART_PUBLIC_API_KEY }} >> .env.local
          echo SITE_URL=${{ secrets.SITE_URL }} >> .env.local
          echo NEXT_PUBLIC_CLOUDINARY_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_NAME }} >> .env.local
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env.local
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env.local
          cat .env.local
      - name: Create .sentryclirc file
        run: |
          touch .sentryclirc
          echo [auth] >> .sentryclirc
          echo token=${{ secrets.SENTRY_AUTH_API }} >> .sentryclirc
          cat .sentryclirc
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-v2-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn lint
      # - run: yarn test:ci
      - run: yarn generate
      - run: yarn run build
      - run: pm2 restart bloomshair-nextapp --watch
    env:
      CI: true
